---
- name: Configuring OSPF on underlay
  nxos_ospf:
    ospf: "{{ ospf_underlay_proc_name }}"

- name: Enabling OSPF on underlay interfaces
  nxos_interface_ospf:
    interface: "{{ item.name }}"
    ospf: "{{ ospf_underlay_proc_name }}"
    area: "0.0.0.0"
    hello_interval: 1
    dead_interval: 4
  loop: "{{ routed_underlay_if[inventory_hostname] }}"
  loop_control:
    label: "{{ item.name }}"
